### ISSUE TITLE
[REQUEST] Events for when someone enters or leaves a zone

### ISSUE THREAD

**Issue by ejm** [pietelite/nope#16]
I'm going to forgo the GitHub template here because I think this is a pretty straightforward request:
I'd like to be able to see programmatically when someone enters or leaves a zone. My particular usecase is an administrative client mod that tells you which zones you're currently in on the F3 debug screen, though I admittedly have a hard time thinking of other uses that wouldn't be more appropriate as settings.

Right now, I can listen to the movement event myself and check if the zones are different (which is what Nope does for entry and exit checks already) but if Nope is already doing that, it'd be convenient to just fire the event at that time. I don't think it's necessary to make those events cancelable but maybe another developer will have a use for that?

Thanks!

**Comment by pietelite** [comment]
So to clarify, you just want the event to have the name of the zone you enter? It would be something like `HostEnterEvent` and `HostExitEvent` with the `MoveEntityEvent` and the name of the `Host` attached, so just a string. It would also fire for changing worlds (`Domain`s).

Does that satisfy your use case?

**Comment by ejm** [comment]
Either that or the whole `Host`/`Domain` object, if possible, yeah! One event for entering, one for leaving.

**Comment by pietelite** [comment]
Well, I don't currently have any plans in elevating the actual `Host` to the API, so unless it's an internal event, I'll just use the name

**Comment by pietelite** [comment]
Added in BETA-2.0
